# Generated by Django 4.0.3 on 2022-11-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='ghhj', upload_to='galary'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='desc',
            field=models.TextField(max_length=220),
        ),
    ]
